import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const envPath = path.join(rootDir, ".env");

const parseEnv = (content) => {
  const lines = content.split(/\r?\n/);
  const out = {};
  for (const line of lines) {
    if (!line || line.trim().startsWith("#")) continue;
    const idx = line.indexOf("=");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1);
    if (key) out[key] = value;
  }
  return out;
};

const base64Url = (input) =>
  Buffer.from(input)
    .toString("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");

const signJwt = (payload, secret) => {
  const header = { alg: "HS256", typ: "JWT" };
  const encodedHeader = base64Url(JSON.stringify(header));
  const encodedPayload = base64Url(JSON.stringify(payload));
  const data = `${encodedHeader}.${encodedPayload}`;
  const signature = base64Url(
    crypto.createHmac("sha256", secret).update(data).digest()
  );
  return `${data}.${signature}`;
};

const randomHex = (bytes) => crypto.randomBytes(bytes).toString("hex");
const randomBase64 = (bytes) => crypto.randomBytes(bytes).toString("base64");

const env = existsSync(envPath) ? parseEnv(await fs.readFile(envPath, "utf8")) : {};

if (!env.JWT_SECRET) env.JWT_SECRET = randomHex(32);
if (!env.POSTGRES_PASSWORD) env.POSTGRES_PASSWORD = randomHex(16);
if (!env.SECRET_KEY_BASE) env.SECRET_KEY_BASE = randomBase64(48);

const now = Math.floor(Date.now() / 1000);
const exp = now + 60 * 60 * 24 * 365 * 10;

if (!env.ANON_KEY) {
  env.ANON_KEY = signJwt({ role: "anon", iss: "supabase-dev", iat: now, exp }, env.JWT_SECRET);
}
if (!env.SERVICE_ROLE_KEY) {
  env.SERVICE_ROLE_KEY = signJwt(
    { role: "service_role", iss: "supabase-dev", iat: now, exp },
    env.JWT_SECRET
  );
}

env.POSTGRES_HOST ??= "db";
env.POSTGRES_DB ??= "postgres";
env.POSTGRES_PORT ??= "5432";

env.KONG_HTTP_PORT ??= "8000";
env.KONG_HTTPS_PORT ??= "8443";

env.PGRST_DB_SCHEMAS ??= "public,storage";

env.SITE_URL ??= "http://localhost:5173";
env.ADDITIONAL_REDIRECT_URLS ??= "http://localhost:5173,http://localhost:4173";
env.JWT_EXPIRY ??= "3600";
env.DISABLE_SIGNUP ??= "false";
env.API_EXTERNAL_URL ??= `http://localhost:${env.KONG_HTTP_PORT}`;

env.MAILER_URLPATHS_CONFIRMATION ??= "/auth/v1/verify";
env.MAILER_URLPATHS_INVITE ??= "/auth/v1/verify";
env.MAILER_URLPATHS_RECOVERY ??= "/auth/v1/verify";
env.MAILER_URLPATHS_EMAIL_CHANGE ??= "/auth/v1/verify";

env.ENABLE_EMAIL_SIGNUP ??= "true";
env.ENABLE_EMAIL_AUTOCONFIRM ??= "true";
env.SMTP_ADMIN_EMAIL ??= "admin@example.com";
env.SMTP_HOST ??= "supabase-mail";
env.SMTP_PORT ??= "2500";
env.SMTP_USER ??= "fake_mail_user";
env.SMTP_PASS ??= "fake_mail_password";
env.SMTP_SENDER_NAME ??= "fake_sender";
env.ENABLE_ANONYMOUS_USERS ??= "false";

env.ENABLE_PHONE_SIGNUP ??= "true";
env.ENABLE_PHONE_AUTOCONFIRM ??= "true";

env.GOOGLE_CLIENT_ID ??= "YOUR_GOOGLE_CLIENT_ID";
env.GOOGLE_CLIENT_SECRET ??= "YOUR_GOOGLE_CLIENT_SECRET";

const knownKeys = new Set([
  "POSTGRES_PASSWORD",
  "JWT_SECRET",
  "ANON_KEY",
  "SERVICE_ROLE_KEY",
  "SECRET_KEY_BASE",
  "POSTGRES_HOST",
  "POSTGRES_DB",
  "POSTGRES_PORT",
  "KONG_HTTP_PORT",
  "KONG_HTTPS_PORT",
  "PGRST_DB_SCHEMAS",
  "SITE_URL",
  "ADDITIONAL_REDIRECT_URLS",
  "JWT_EXPIRY",
  "DISABLE_SIGNUP",
  "API_EXTERNAL_URL",
  "MAILER_URLPATHS_CONFIRMATION",
  "MAILER_URLPATHS_INVITE",
  "MAILER_URLPATHS_RECOVERY",
  "MAILER_URLPATHS_EMAIL_CHANGE",
  "ENABLE_EMAIL_SIGNUP",
  "ENABLE_EMAIL_AUTOCONFIRM",
  "SMTP_ADMIN_EMAIL",
  "SMTP_HOST",
  "SMTP_PORT",
  "SMTP_USER",
  "SMTP_PASS",
  "SMTP_SENDER_NAME",
  "ENABLE_ANONYMOUS_USERS",
  "ENABLE_PHONE_SIGNUP",
  "ENABLE_PHONE_AUTOCONFIRM",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
]);

const extraLines = Object.keys(env)
  .filter((key) => !knownKeys.has(key))
  .map((key) => `${key}=${env[key]}`);

const envLines = [
  "# Generated by scripts/setup-dev.mjs",
  "",
  "POSTGRES_PASSWORD=" + env.POSTGRES_PASSWORD,
  "JWT_SECRET=" + env.JWT_SECRET,
  "ANON_KEY=" + env.ANON_KEY,
  "SERVICE_ROLE_KEY=" + env.SERVICE_ROLE_KEY,
  "SECRET_KEY_BASE=" + env.SECRET_KEY_BASE,
  "",
  "POSTGRES_HOST=" + env.POSTGRES_HOST,
  "POSTGRES_DB=" + env.POSTGRES_DB,
  "POSTGRES_PORT=" + env.POSTGRES_PORT,
  "",
  "KONG_HTTP_PORT=" + env.KONG_HTTP_PORT,
  "KONG_HTTPS_PORT=" + env.KONG_HTTPS_PORT,
  "",
  "PGRST_DB_SCHEMAS=" + env.PGRST_DB_SCHEMAS,
  "",
  "SITE_URL=" + env.SITE_URL,
  "ADDITIONAL_REDIRECT_URLS=" + env.ADDITIONAL_REDIRECT_URLS,
  "JWT_EXPIRY=" + env.JWT_EXPIRY,
  "DISABLE_SIGNUP=" + env.DISABLE_SIGNUP,
  "API_EXTERNAL_URL=" + env.API_EXTERNAL_URL,
  "",
  "MAILER_URLPATHS_CONFIRMATION=" + env.MAILER_URLPATHS_CONFIRMATION,
  "MAILER_URLPATHS_INVITE=" + env.MAILER_URLPATHS_INVITE,
  "MAILER_URLPATHS_RECOVERY=" + env.MAILER_URLPATHS_RECOVERY,
  "MAILER_URLPATHS_EMAIL_CHANGE=" + env.MAILER_URLPATHS_EMAIL_CHANGE,
  "",
  "ENABLE_EMAIL_SIGNUP=" + env.ENABLE_EMAIL_SIGNUP,
  "ENABLE_EMAIL_AUTOCONFIRM=" + env.ENABLE_EMAIL_AUTOCONFIRM,
  "SMTP_ADMIN_EMAIL=" + env.SMTP_ADMIN_EMAIL,
  "SMTP_HOST=" + env.SMTP_HOST,
  "SMTP_PORT=" + env.SMTP_PORT,
  "SMTP_USER=" + env.SMTP_USER,
  "SMTP_PASS=" + env.SMTP_PASS,
  "SMTP_SENDER_NAME=" + env.SMTP_SENDER_NAME,
  "ENABLE_ANONYMOUS_USERS=" + env.ENABLE_ANONYMOUS_USERS,
  "",
  "ENABLE_PHONE_SIGNUP=" + env.ENABLE_PHONE_SIGNUP,
  "ENABLE_PHONE_AUTOCONFIRM=" + env.ENABLE_PHONE_AUTOCONFIRM,
  "",
  "GOOGLE_CLIENT_ID=" + env.GOOGLE_CLIENT_ID,
  "GOOGLE_CLIENT_SECRET=" + env.GOOGLE_CLIENT_SECRET,
  "",
  ...extraLines,
  extraLines.length ? "" : "",
].join("\n");

await fs.writeFile(envPath, envLines, "utf8");

const appEnvPath = path.join(rootDir, "apps", "boladas", ".env");
const appEnvLines = [
  "VITE_API_URL=http://localhost:8787",
  `VITE_SUPABASE_URL=http://localhost:${env.KONG_HTTP_PORT}`,
  `VITE_SUPABASE_ANON_KEY=${env.ANON_KEY}`,
  "VITE_AUTH_ENABLED_PROVIDERS=google,azure,facebook",
  "",
].join("\n");

await fs.writeFile(appEnvPath, appEnvLines, "utf8");
